export default {
  login_title: 'Login Page',
  login_lbl: 'Login',
  email_error_message: 'Please Enter Valid Email',
  name_error_message: 'Please Enter Valid Name',
  gender_error_message: "Gender Can't be Empty ",
  gender_title: 'Choose Gender Title',
  gender_lbl: 'Gender',
  email_lbl: 'Email',
  name_lbl: 'Name',
  relation_lbl: 'Relation',
  relation_title: 'Choose Relation Title',
  relation_error_message: "Relation Can't be Empty ",
  date_error_message: "Date Can't be Null ",
  date_lbl: 'Date',
  date_less_than_lbl: 'Less Than Date',
  date_greater_than_lbl: 'Greater Than Date',
  date_current_lbl: 'Current Date',
  min_date_error_message: 'Please Select the date above 01 Jan 2023',
  max_date_error_message: 'Please Select the date below 01 Jan 2024',
  datetimepicker_mode_date: 'Date',
  datetimepicker_mode_time: 'Time',
};
